# Generated by Django 4.2.5 on 2023-10-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isactive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BandSongsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.IntegerField(blank=True, null=True)),
                ('song_name', models.CharField(blank=True, max_length=200, null=True)),
                ('song_artist', models.CharField(blank=True, max_length=200, null=True)),
                ('song_genre', models.CharField(blank=True, max_length=200, null=True)),
                ('song_durations', models.CharField(blank=True, max_length=200, null=True)),
                ('song_year', models.CharField(blank=True, max_length=200, null=True)),
                ('song_cover', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='band_covers')),
                ('cortes', models.CharField(blank=True, max_length=200, null=True)),
                ('bpm', models.CharField(blank=True, max_length=200, null=True)),
                ('song_lyrics', models.TextField(blank=True, null=True)),
                ('band_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandleader')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShowStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_show_started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SongsInSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sets')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('SongsInSet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.songsinset')),
            ],
        ),
        migrations.CreateModel(
            name='LikedBandSongsListInAllVenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('band_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venue')),
            ],
        ),
        migrations.CreateModel(
            name='LikedBandSongsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('band_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('song_decicated_to', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
            ],
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isactive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
