# Generated by Django 4.2 on 2023-04-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='song_dedicated_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
