# Generated by Django 4.2.5 on 2023-10-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_venue_address_venue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.venue'),
        ),
    ]
