# Generated by Django 4.2 on 2023-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_songsset'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsongslist',
            name='song_year',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
