# Generated by Django 4.2 on 2023-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customerrequest_song_dedicated_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='request_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='song_requested_count',
            field=models.IntegerField(default=0),
        ),
    ]
