# Generated by Django 4.2 on 2023-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bandsongslist_song_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandsongslist',
            name='song_cover',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='band_covers'),
        ),
    ]
