# Generated by Django 4.2.5 on 2023-11-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sets_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='date',
            new_name='city',
        ),
        migrations.AddField(
            model_name='venue',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
