# Generated by Django 4.2 on 2023-04-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customerrequest_request_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='song_requested_count',
        ),
    ]
