# Generated by Django 4.2 on 2023-05-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bandsongslist_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsongslist',
            name='bpm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bandsongslist',
            name='cortes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
