# Generated by Django 4.2 on 2023-04-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customerrequest_song_requested_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedBandSongsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('band_songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
