# Generated by Django 4.2 on 2023-05-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bandsongslist_bpm_bandsongslist_cortes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Setname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SongsInSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sets')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
            ],
        ),
    ]
