# Generated by Django 4.2 on 2023-06-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sets_songsinset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
