# Generated by Django 4.2 on 2023-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_band_songs_likedbandsongslist_band_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsongslist',
            name='song_cover',
            field=models.ImageField(blank=True, null=True, upload_to='band_covers'),
        ),
        migrations.AddField(
            model_name='bandsongslist',
            name='song_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
