# Generated by Django 4.2.5 on 2023-11-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sets_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
