# Generated by Django 4.2 on 2023-06-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedbandsongslist',
            name='customer',
        ),
    ]
