# Generated by Django 5.0.3 on 2024-04-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
