# Generated by Django 4.2 on 2023-06-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_likedbandsongslist_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrequest',
            old_name='song_decicated_by',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='customerrequest',
            name='customer',
        ),
    ]
