# Generated by Django 4.2 on 2023-06-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_song_decicated_by_customerrequest_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sets')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bandsongslist')),
            ],
        ),
    ]
