# Generated by Django 4.2 on 2023-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsinset',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
