# Generated by Django 4.2 on 2023-06-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_songsinset_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='number',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='set',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
        migrations.AddField(
            model_name='playlist',
            name='SongsInSet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.songsinset'),
        ),
    ]
