# Generated by Django 4.2 on 2023-06-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customerrequest_is_approved_customerrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsinset',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
