# Generated by Django 4.2 on 2023-06-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_songsinset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsongslist',
            name='song_lyrics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
