# Generated by Django 4.2.2 on 2023-07-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_venue_alter_bandsongslist_song_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsongslist',
            name='song_pdf',
            field=models.FileField(blank=True, null=True, upload_to='band_songs'),
        ),
    ]
