# Generated by Django 4.2.2 on 2023-07-04 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_bandsongslist_song_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandsongslist',
            name='song_pdf',
        ),
    ]
