# Generated by Django 4.2.4 on 2023-09-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_likedbandsongslistinallvenues'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
